# Generated by Django 5.2.7 on 2025-10-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participanteconta',
            unique_together=set(),
        ),
    ]
