# Generated by Django 5.2.7 on 2025-10-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_alter_participanteconta_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status_conta',
            field=models.CharField(choices=[('AGUARDANDO_APROVACAO', 'Aguardando Aprovacao'), ('PARCIALMENTE_PAGA', 'Aprovado'), ('NAO_APROVADO', 'Nao Aprovado')], default='NAO_APROVADO', max_length=20),
        ),
    ]
