# Generated by Django 5.2.7 on 2025-10-23 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_usuario_status_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='status_conta',
            new_name='status_associacao',
        ),
    ]
